### ISSUE TITLE
Syntax for defining input and output

### ISSUE THREAD

**Issue by almarklein** [almarklein/python-shader#11]
## Introduction

Shader entrypoints have IO:

* input: Builtin inputs
* output: Builtin outputs
* input: Per-vertex data input (vertex shader only)
* output: Per-vertex output (vertex shader only)
* input: Per-fragment data input, interpolated from the above (fragment shader only)
* resource: Buffers (r/w)
* resource: Textures (r/w resource)
* resource: Samplers (r/w resource)
* Specialization constants (constants set post-compile-time)

References:
* https://gpuweb.github.io/WSL/
* https://github.com/gpuweb/WSL/blob/master/Examples/passthrough.whlsl

How do we want to spell these out? There's always three and sometimes more "attributes" to an i/o variable:
* Its name within the function
* Its binding slot (or builtin name)
* Its type
* (its offset)

## A few options

In the below examples, I write the triangle vertex shader, and a (hypothetical) compute shader that calculates the average of three values (from a buffer) and writes it back to a buffer.

### The current version

In the current approach, you call `define` on `input` / `output`, passing `name`, `slot`, `type`. The actual value is then accessible as an attribute of the `input` or `output` object.

Cons:
* I will definitely forget the order of the `define` arguments.
* May be annoying that you'd need another line to give a variable a short name.
* I find having strings in a shader slightly inelegant.

```py
@python2shader
def vertex_shader(input, output):

    input.define("index", "VertexId", i32)
    output.define("pos", "Position", vec4)
    output.define("color", 0, vec3)

    positions = [vec2(+0.0, -0.5), vec2(+0.5, +0.5), vec2(-0.5, +0.7)]
    p = positions[input.index]

    output.pos = vec4(p, 0.0, 1.0)
    output.color = vec3(p, 0.5)

@python2shader
def compute_shader(input, buffers):
    input.define("offset", "SomeBuiltinIndex", i32)
    buffers.define("pos3dArray", 0, Array(vec3)  # read
    buffers.define("avgArray", 1, Array(f32))  # write

    pos3d = buffers.pos3dArray[input.offset]
    buffers.avgArray[offset] = (pos3d.x + pos3d.y + pos3d.z) / z
```

### Using indexing

This can also be written using indexing. Indexing works well here because it can be used as a getter and a setter. You also assign directly to the local name, which is nice.

Cons:

* Users can do `output[0, vec3] = vec3(p, 0.5)`, which makes the code less readable because it moves binding definitions to the bottom of the shader, and there is no local variable name to add semantics. We can tell users to avoid it but ... 
* I find having strings in a shader slightly inelegant.

```py
@python2shader
def vertex_shader(input, output):

    index = input["VertexId", i32]
    outpos = output["Position", vec4]
    outcolor = output[0, vec3]

    positions = [vec2(+0.0, -0.5), vec2(+0.5, +0.5), vec2(-0.5, +0.7)]
    p = positions[index]

    outpos.xyzw = vec4(p, 0.0, 1.0)
    outcolor.rgb = vec3(p, 0.5)


@python2shader
def compute_shader(input, buffers):
    offset = input["SomeBuiltinIndex", i32]
    pos3dArray = buffers[0, Array(vec3)]
    avgArray = buffers[1, Array(f32)]

    pos3d = pos3dArray[offset]
    avgArray[offset] = (pos3d.x + pos3d.y + pos3d.z) / 3
```

### Put definitions in the function signature - as object

This looks quite Pythonic, and opens up the possibility to define io binding outside of the function.

Cons:
* Outputs bindings being specified as input args may feel a bit weird. 
* Users may also expect this to work `outcolor = ...`, but we should not. I think we should raise an error for this syntax.
* Need extra classes for `Input` etc.

```py
@python2shader
def vertex_shader(
    index: Input("VertexId", i32),
    outpos: Output("Position", vec4),
    outcolor: Output(0, vec3),
):
    positions = [vec2(+0.0, -0.5), vec2(+0.5, +0.5), vec2(-0.5, +0.7)]
    p = positions[index]

    outpos.xyzw = vec4(p, 0.0, 1.0)
    outcolor.rgb = vec3(p, 0.5)


@python2shader
def compute_shader(
    offset: Input("SomeBuiltinIndex", i32),
    pos3dArray: BufferIO(0, Array(vec3)),
    avgArray: BufferIO(1, Array(f32)),
):
    pos3d = pos3dArray[offset]
    avgArray[offset] = (pos3d.x + pos3d.y + pos3d.z) / 3
```

### Put definitions in the function signature - as 3-tuple

Compared to the above, we don't need additional classes, so it feels more "lightweight", but it may be harder to remember the order of the elements.

```py
@python2shader
def vertex_shader(
    index: ("input", "VertexId", i32),
    outpos: ("output", Position", vec4),
    outcolor: ("output", 0, vec3),
):
    positions = [vec2(+0.0, -0.5), vec2(+0.5, +0.5), vec2(-0.5, +0.7)]
    p = positions[index]

    outpos.xyzw = vec4(p, 0.0, 1.0)
    outcolor.rgb = vec3(p, 0.5)


@python2shader
def compute_shader(
    offset: ("input", "SomeBuiltinIndex", i32),
    pos3dArray: ("buffer", 0, Array(vec3)),
    avgArray: ("buffer", 1, Array(f32)),
):
    pos3d = pos3dArray[offset]
    avgArray[offset] = (pos3d.x + pos3d.y + pos3d.z) / 3
```

### Put definitions in the function signature - as 2-tuple

Also no classes, but make it somewhat "easier" by combining the resource type with the resource binding. This feels kinda natural, I think?

```py
@python2shader
def vertex_shader(
    index: ("input:VertexId", i32),
    outpos: ("output:Position", vec4),
    outcolor: ("output:0", vec3),
):
    positions = [vec2(+0.0, -0.5), vec2(+0.5, +0.5), vec2(-0.5, +0.7)]
    p = positions[index]

    outpos.xyzw = vec4(p, 0.0, 1.0)
    outcolor.rgb = vec3(p, 0.5)


@python2shader
def compute_shader(
    offset: ("input:SomeBuiltinIndex", i32),
    pos3dArray: ("buffer:0", Array(vec3)),
    avgArray: ("buffer:1", Array(f32)),
):
    pos3d = pos3dArray[offset]
    avgArray[offset] = (pos3d.x + pos3d.y + pos3d.z) / 3
```

**Comment by almarklein** [comment]
Leaning towards the last option.

**Comment by almarklein** [comment]
I think this needs more time to sink in and refine. And I want to write a few more shaders (also a compute shader) before making a decision.

**Comment by Korijn** [comment]
Just adding a flavor for you to consider (haven't really got a clue about the internals at play here so please consider it just a brainfart)

```python
@python2shader(inputs={"VertexId": i32}, outputs={"Position": vec4, 0: vec3})
def vertex_shader(inputs, outputs):
    positions = [vec2(+0.0, -0.5), vec2(+0.5, +0.5), vec2(-0.5, +0.7)]
    p = positions[inputs.VertexId]

    outputs.Position.xyzw = vec4(p, 0.0, 1.0)
    outputs.0.rgb = vec3(p, 0.5)
```

**Comment by almarklein** [comment]
I think I want the io definitions to be part of the function object, so putting it in the decorator might be a bit too far "up" :)

I put more examples above, basically flavors of using type annotations. I think I like the 2-tuple most; a normal type annotation tells "what the data is". We need to know "what the data is", and "where it comes from". We can fit that into a single string object relatively easily ...

**Comment by Korijn** [comment]
"Put definitions in the function signature - as object" looks most natural to me :) love these new ideas!

**Comment by almarklein** [comment]
> ... because it relies on a string format convention

Good point. It seems nice and simple, but it introduces new conventions to remember.

**Comment by Korijn** [comment]
I also like the 3-tuple, but the first component is just a limited set of choices (like the third component) so it is a little awkward that it's a string? How about:

```
    index: (wgpu.INPUT, "VertexId", i32),
    outpos: (wgpu.OUTPUT, "Position", vec4),
    outcolor: (wgpu.OUTPUT, 0, vec3),
```

Just using constants or an enum? Obviously if you import them differently you can leave out the prefix `wpgu.`

**Comment by almarklein** [comment]
Nice one, discoverability is indeed another plus for the "object-version", and using an enum brings that to the tuple-version. mmm ...

**Comment by Korijn** [comment]
Yeah or just predefined constants, like `i32`, `vec4` etc are as well

**Comment by almarklein** [comment]
With #19 both the object-version and 3-tuple version are supported. We still need to decide on one (or e.g. a namedtuple) and refine it a bit.
